# -*- coding: utf-8 -*-
"""Internnova task 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c-pXHzsuZQFWVJvLnkN06z_9BwuXDMLZ
"""

print("Welcome to Python Data Analytics")

name=input("Enter Your Name:")
college=input("Enter your college name:")
branch=input("Enter your Branch:")

print("\n--------------- Student Information ---------------")
print("Name:",name)
print("College:",college)
print("Branch:",branch)
print("------------------------------------------------")