# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TTtH10CjydKNHfKukZ_F3giD83fCj8JZ
"""

print("Numbers from 1 to 20:")

for i in range(1, 21):
    print(i)

num = int(input("Enter a number: "))

print("\nMultiplication Table")

for i in range(1, 11):
    print(num, "x", i, "=", num * i)
i = 2

print("\n Even numbers from 1 to 50:")

while i <= 50:
    print(i)
    i += 2