# -*- coding: utf-8 -*-
"""Internnova task 4 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v7GmNfkVYH8tAcb46LVgI6LPIiRE1DTk
"""

marks = float(input("Enter your marks: "))

if marks >= 90:
    grade = "A"
elif marks >= 75:
    grade = "B"
elif marks >= 60:
    grade = "C"
else:
    grade = "Fail"

print("Your Grade is:", grade)