# -*- coding: utf-8 -*-
"""Internnova task 7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YCYVa3UuzEG_wFNBdHwyBwmISVJXE_-m
"""

#====================================== String =================================
text = "Python Data Analytics"

print("Original:", text)
print("Uppercase:", text.upper())
print("Lowercase:", text.lower())
print("Replace:", text.replace("Python", "Excel"))
print("Position of Data:", text.find("Data"))

#================================= List ========================================
numbers = [10, 20, 30, 40]

print("\n")
print("Original list:", numbers)

numbers.append(50)
print("After append:", numbers)

numbers.remove(20)
print("After remove:", numbers)

numbers.sort()
print("After sort:", numbers)

#=============================== Tuple =========================================
subjects = ("Python", "SQL", "Power BI", "Excel")
print("\n")
print("Tuple:", subjects)
print("First subject:", subjects[0])
print("Second subject:", subjects[1])

#============================ Dictionary =======================================
student = {
    "Name": "Tejaswi",
    "College": "JNTUK",
    "Branch": "CSE",
    "CGPA": 8.26
}
print("\n")
print("Student Information:")
print(student)
print("Name:", student["Name"])
print("College:", student["College"])
print("Branch:", student["Branch"])
print("CGPA:", student["CGPA"])
skills = {"Python", "SQL", "Excel"}

print("Original set:", skills)

#=============================== Set ===========================================
skills.add("Power BI")
print("\n")
print("After add:", skills)

skills.remove("Excel")
print("After remove:", skills)