# -*- coding: utf-8 -*-
"""InternNova task 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dvOi5PUixYzU95IUIwrNXtYu0pwSuWqL
"""

num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))

print("\n----- Calculator -----")
print("Addition:", num1 + num2)
print("Subtraction:", num1 - num2)
print("Multiplication:", num1 * num2)

if num2 != 0:
    print("Division:", num1 / num2)
    print("Modulus:", num1 % num2)
else:
    print("Division: Cannot divide by zero")
    print("Modulus: Cannot divide by zero")