# -*- coding: utf-8 -*-
"""Internnova task6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oCZwSm0RuZ6ZncPXXXk5-OPdxZ3RH82b
"""

def calculate_square(number):
    return number * number


def calculate_average(a, b, c):
    return (a + b + c) / 3


num = float(input("Enter a number: "))
print("Square:", calculate_square(num))

print("\nEnter three numbers:")
a = float(input("First number: "))
b = float(input("Second number: "))
c = float(input("Third number: "))

print("Average:", calculate_average(a, b, c))