# -*- coding: utf-8 -*-
"""Internnova task 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t3vD0-lrJQXWt7ZueFCerRLVu102jaEy
"""

age = 20
cgpa = 8.26
name = "Saga Tejaswi"
is_student = True

print("Age:", age)
print("Data Type:", type(age))

print("\nCGPA:", cgpa)
print("Data Type:", type(cgpa))

print("\nName:", name)
print("Data Type:", type(name))

print("\nStudent:", is_student)
print("Data Type:", type(is_student))