# -*- coding: utf-8 -*-
"""Internnova task8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SJNlSWT7D44hYP3Kh8VManc9ypvwjIUs
"""

filename = "introduction.txt"

# Create and write to the file
with open(filename, "w") as file:
    file.write("Hello! My name is Saga Tejaswi Lakshmi Priya Durga.\n")
    file.write("I am a B.Tech Computer Science student with a CGPA of 8.26\n")
    file.write("I am interested in Data Analytics and Business Intelligence.\n")
    file.write("I am learning Python, SQL, Excel and Power BI.\n")

# Read and display the file
with open(filename, "r") as file:
    content = file.read()

print("----- File Contents -----")
print(content)